[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
pretty_assertions = "1.4.0"
smol_str = "0.2.0"
thiserror = "1.0.50"

[workspace.package]
authors = ["Clay66 <clayw@clay66.dev>"]
license = "MIT"
