[package]
name = "ocrlang"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hir = { path = "../hir", package = "ocrlang_hir" }
parser = { path = "../parser", package = "ocrlang_parser" }
ast = { path = "../ast", package = "ocrlang_ast" }
interpreter = { version = "0.1.0", path = "../interpreter", package = "ocrlang_interpreter" }
