name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest
    - name: Test
      run: cargo nextest run --no-fail-fast --verbose

